# Generated by Django 5.1.2 on 2024-10-26 05:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='business',
            name='google_business_id',
            field=models.CharField(default='default_id', max_length=50),
        ),
    ]
